# Copyright (c) 2023-2025 [Ribose Inc](https://www.ribose.com).
# All rights reserved.
# This file is a part of tebako
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

name: test-and-release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  CODECOV_TOKEN: 66eec255-1b3b-40a9-9ac3-30d76233c812

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.7
        bundler-cache: true

    - name: Rubocop
      run: bundle exec rubocop

  test:
    name: Ruby ${{ matrix.ruby_ver }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-22.04', 'macos-13', 'macos-14', 'windows-latest' ]
        ruby_ver: [ '2.7.8', '3.0.7', '3.1.6', '3.2.7', '3.3.7', '3.4.1' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_ver }}
        bundler-cache: true

    - name: Test
      run: bundle exec rake

    - name: Upload coverage to Codecov
      if: matrix.ruby_ver == '3.3.7'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ env.CODECOV_TOKEN }}

  test-container:
    name: Ruby on ${{ matrix.os }}
    container:
      image: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'alpine:3.17', 'alpine:3.19' ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby
      run: |
        apk --no-cache --upgrade add build-base cmake git bash   \
        autoconf make binutils-dev pkgconfig tar ruby-dev        \
        openjdk11-jre-headless linux-headers libffi-dev

    - name: Install bundler
      shell: bash
      run: gem install bundler

    - name: Install bundle
      shell: bash
      run: bundle install

    - name: Test
      run: bundle exec rake

# ----- Release -----
  release:
    name: Release gem
    needs: [ test, test-container ]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - uses: cadwallion/publish-rubygems-action@master
      env:
        RUBYGEMS_API_KEY: ${{secrets.TEBAKO_CI_RUBYGEMS_API_KEY}}
